name: Documentation

on:
  push:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: write  # required to push to gh-pages

jobs:
  docs:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Build Sphinx (HTML)
        run: sphinx-build -M html docs/pages _build

      - name: Prepare slides folders (optional)
        run: |
          mkdir -p _build/html/slides/_static
          if [ -d docs/slides/_static ]; then
            cp -r docs/slides/_static/* _build/html/slides/_static/ || true
          fi

      - name: Fetch reveal.js (local copy)
        run: |
          sudo apt-get update && sudo apt-get install -y unzip
          wget -q https://github.com/hakimel/reveal.js/archive/refs/tags/4.3.1.zip
          unzip -q 4.3.1.zip
          mkdir -p _build/html/slides/reveal.js
          mv reveal.js-4.3.1/* _build/html/slides/reveal.js

      - name: Build slides with Pandoc (all .md files)
        run: |
          shopt -s nullglob
          for f in docs/slides/*.md; do
            out="_build/html/slides/$(basename "${f%.md}").html"
            docker run --rm -v "$PWD":/data pandoc/core:3.1 \
              --standalone \
              --from=markdown \
              --to=revealjs \
              --slide-level=2 \
              -V theme="simple" \
              -V transition="linear" \
              -V revealjs-url=https://unpkg.com/reveal.js@4/ \
              -V keyboard="{37:'prev',38:'prev',39:'next',40:'next'}" \
              --output="$out" \
              "$f"
          done

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: _build/html
